graph TD
    subgraph 桥梁定理
        BRIDGE__BT-1["BT-1"]
        style BRIDGE__BT-1 fill:#e74c3c
        BRIDGE__BT-2["BT-2"]
        style BRIDGE__BT-2 fill:#e74c3c
        BRIDGE__BT-3["BT-3"]
        style BRIDGE__BT-3 fill:#e74c3c
        BRIDGE__BT-4["BT-4"]
        style BRIDGE__BT-4 fill:#e74c3c
        BRIDGE__BT-5["BT-5"]
        style BRIDGE__BT-5 fill:#e74c3c
        BRIDGE__BT-4-C["BT-4-C"]
        style BRIDGE__BT-4-C fill:#e74c3c
        BRIDGE__BT-3-C["BT-3-C"]
        style BRIDGE__BT-3-C fill:#e74c3c
        BRIDGE__BT-3-A["BT-3-A"]
        style BRIDGE__BT-3-A fill:#e74c3c
    end

    BRIDGE__BT-4 --> BRIDGE__BT-4-C