graph TD
    subgraph 引理
        MD__BRIDGE_THEOREMS_DEEPENED__BT-1-A["BT-1-A"]
        style MD__BRIDGE_THEOREMS_DEEPENED__BT-1-A fill:#9e9c9e
        MD__BRIDGE_THEOREMS_DEEPENED__BT-1-B["BT-1-B"]
        style MD__BRIDGE_THEOREMS_DEEPENED__BT-1-B fill:#9e9c9e
        MD__BRIDGE_THEOREMS_DEEPENED__BT-1-C["BT-1-C"]
        style MD__BRIDGE_THEOREMS_DEEPENED__BT-1-C fill:#9e9c9e
        MD__BRIDGE_THEOREMS_DEEPENED__BT-2-A["BT-2-A"]
        style MD__BRIDGE_THEOREMS_DEEPENED__BT-2-A fill:#9e9c9e
        MD__BRIDGE_THEOREMS_DEEPENED__BT-2-B["BT-2-B"]
        style MD__BRIDGE_THEOREMS_DEEPENED__BT-2-B fill:#9e9c9e
        MD__BRIDGE_THEOREMS_DEEPENED__BT-2-C["BT-2-C"]
        style MD__BRIDGE_THEOREMS_DEEPENED__BT-2-C fill:#9e9c9e
        MD__BRIDGE_THEOREMS_DEEPENED__BT-3-A["BT-3-A"]
        style MD__BRIDGE_THEOREMS_DEEPENED__BT-3-A fill:#9e9c9e
        MD__BRIDGE_THEOREMS_DEEPENED__BT-3-B["BT-3-B"]
        style MD__BRIDGE_THEOREMS_DEEPENED__BT-3-B fill:#9e9c9e
        MD__BRIDGE_THEOREMS_DEEPENED__BT-3-C["BT-3-C"]
        style MD__BRIDGE_THEOREMS_DEEPENED__BT-3-C fill:#9e9c9e
        MD__BRIDGE_THEOREMS_DEEPENED__BT-4-A["BT-4-A"]
        style MD__BRIDGE_THEOREMS_DEEPENED__BT-4-A fill:#9e9c9e
    end
