```mermaid
graph TD
    subgraph 桥梁定理
        BRIDGE__BT-1["BT-1"]
        style BRIDGE__BT-1 fill:#e74c3c
        BRIDGE__BT-2["BT-2"]
        style BRIDGE__BT-2 fill:#e74c3c
        BRIDGE__BT-3["BT-3"]
        style BRIDGE__BT-3 fill:#e74c3c
        BRIDGE__BT-4["BT-4"]
        style BRIDGE__BT-4 fill:#e74c3c
        BRIDGE__BT-5["BT-5"]
        style BRIDGE__BT-5 fill:#e74c3c
        BRIDGE__BT-1-A["BT-1-A"]
        style BRIDGE__BT-1-A fill:#e74c3c
        BRIDGE__BT-1-B["BT-1-B"]
        style BRIDGE__BT-1-B fill:#e74c3c
        BRIDGE__BT-1-C["BT-1-C"]
        style BRIDGE__BT-1-C fill:#e74c3c
        BRIDGE__BT-2-A["BT-2-A"]
        style BRIDGE__BT-2-A fill:#e74c3c
        BRIDGE__BT-2-B["BT-2-B"]
        style BRIDGE__BT-2-B fill:#e74c3c
        BRIDGE__BT-2-C["BT-2-C"]
        style BRIDGE__BT-2-C fill:#e74c3c
        BRIDGE__BT-3-A["BT-3-A"]
        style BRIDGE__BT-3-A fill:#e74c3c
        BRIDGE__BT-3-B["BT-3-B"]
        style BRIDGE__BT-3-B fill:#e74c3c
        BRIDGE__BT-3-C["BT-3-C"]
        style BRIDGE__BT-3-C fill:#e74c3c
        BRIDGE__BT-4-A["BT-4-A"]
        style BRIDGE__BT-4-A fill:#e74c3c
        BRIDGE__BT-4-B["BT-4-B"]
        style BRIDGE__BT-4-B fill:#e74c3c
        BRIDGE__BT-4-C["BT-4-C"]
        style BRIDGE__BT-4-C fill:#e74c3c
        BRIDGE__BT-5-A["BT-5-A"]
        style BRIDGE__BT-5-A fill:#e74c3c
        BRIDGE__BT-5-B["BT-5-B"]
        style BRIDGE__BT-5-B fill:#e74c3c
        BRIDGE__BT-5-C["BT-5-C"]
        style BRIDGE__BT-5-C fill:#e74c3c
    end
    BRIDGE__BT-1 --> BRIDGE__BT-1-A
    BRIDGE__BT-1 --> BRIDGE__BT-1-B
    BRIDGE__BT-1 --> BRIDGE__BT-1-C
    BRIDGE__BT-2 --> BRIDGE__BT-2-A
    BRIDGE__BT-2 --> BRIDGE__BT-2-B
    BRIDGE__BT-2 --> BRIDGE__BT-2-C
    BRIDGE__BT-2 --> BRIDGE__BT-1
    BRIDGE__BT-3 --> BRIDGE__BT-3-A
    BRIDGE__BT-3 --> BRIDGE__BT-3-B
    BRIDGE__BT-3 --> BRIDGE__BT-3-C
    BRIDGE__BT-3 --> BRIDGE__BT-1
    BRIDGE__BT-3 --> BRIDGE__BT-2
    BRIDGE__BT-4 --> BRIDGE__BT-4-A
    BRIDGE__BT-4 --> BRIDGE__BT-4-B
    BRIDGE__BT-4 --> BRIDGE__BT-4-C
    BRIDGE__BT-4 --> BRIDGE__BT-2
    BRIDGE__BT-4 --> BRIDGE__BT-3
    BRIDGE__BT-5 --> BRIDGE__BT-5-A
    BRIDGE__BT-5 --> BRIDGE__BT-5-B
    BRIDGE__BT-5 --> BRIDGE__BT-5-C
    BRIDGE__BT-5 --> BRIDGE__BT-1
    BRIDGE__BT-5 --> BRIDGE__BT-3
```