/*
 * Auto-generated from: 03_System_Technology_Domains\02_Cbindgen_Usage.md
 * Line: 684
 * Language: c
 * Block ID: 3c3a1991
 * 
 * This file was automatically extracted from the C_Lang knowledge base.
 * DO NOT MODIFY - Changes will be overwritten on next extraction.
 */

/* Auto-generated by cbindgen */

#ifndef RL_BINDINGS_H
#define RL_BINDINGS_H

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>

/**
 * A 2D point
 */
typedef struct {
    double x;
    double y;
} RlPoint;

/**
 * Status codes for operations
 */
typedef enum {
    RL_STATUS_OK = 0,
    RL_STATUS_ERROR = 1,
    RL_STATUS_INVALID_INPUT = 2,
    RL_STATUS_OUT_OF_MEMORY = 3,
    RL_STATUS_NOT_FOUND = 4,
} RlStatus;

/**
 * Opaque handle to a database connection
 */
typedef struct RlDatabase RlDatabase;

/**
 * Thread-safe counter
 */
typedef struct RlCounter RlCounter;

/**
 * Callback type for iteration
 */
typedef void (*RlIterCallback)(const char *item, void *user_data);

#ifdef __cplusplus
extern "C" {
#endif // __cplusplus

/**
 * Adds two integers
 */
int rl_add(int a, int b);

/**
 * Divides two floats
 * Returns 0.0 if b is 0
 */
double rl_divide(double a, double b);

/**
 * Creates a new point
 */
RlPoint rl_point_new(double x, double y);

/**
 * Calculates distance between two points
 */
double rl_point_distance(const RlPoint *a, const RlPoint *b);

/**
 * Returns status as string
 */
const char *rl_status_string(RlStatus status);

/**
 * Creates a new database handle
 * conn_str must be a valid null-terminated UTF-8 string
 */
RlDatabase *rl_db_create(const char *conn_str);

/**
 * Destroys a database handle
 * db must be a valid pointer returned by rl_db_create
 * After calling, db becomes invalid and must not be used
 */
void rl_db_destroy(RlDatabase *db);

/**
 * Connects to the database
 */
RlStatus rl_db_connect(RlDatabase *db);

/**
 * Returns a greeting message
 * Caller must free the returned string using rl_string_free
 */
char *rl_greet(const char *name);

/**
 * Frees a string allocated by the library
 */
void rl_string_free(char *s);

/**
 * Iterates over items and calls callback for each
 */
void rl_iterate(RlIterCallback callback, void *user_data);

/**
 * Sum of integer array
 */
int rl_array_sum(const int *data, size_t len);

/**
 * Sorts an array in place
 */
void rl_array_sort(int *data, size_t len);

/**
 * Creates a new counter
 */
RlCounter *rl_counter_new(void);

/**
 * Destroys a counter
 */
void rl_counter_destroy(RlCounter *counter);

/**
 * Increments the counter
 */
int64_t rl_counter_increment(RlCounter *counter);

/**
 * Gets the current value
 */
int64_t rl_counter_get(RlCounter *counter);

#ifdef __cplusplus
} // extern "C"
#endif // __cplusplus

#endif /* RL_BINDINGS_H */
