/*
 * Auto-generated from: 01_Core_Knowledge_System\09_Safety_Standards\MISRA_C_2025\04_MISRA_C_2025_Rules_16-22.md
 * Line: 537
 * Language: c
 * Block ID: 17154e80
 * 
 * This file was automatically extracted from the C_Lang knowledge base.
 * DO NOT MODIFY - Changes will be overwritten on next extraction.
 */

/* 自动生成 - 请勿手动修改 */
/* Generated by ToolX v2.1.0 on 2026-03-18 */
