/*
 * Auto-generated from: 03_System_Technology_Domains\16_Rust_Interoperability\README.md
 * Line: 406
 * Language: c
 * Block ID: 5c2deb7c
 * 
 * This file was automatically extracted from the C_Lang knowledge base.
 * DO NOT MODIFY - Changes will be overwritten on next extraction.
 */

/* Auto-generated by cbindgen */

#ifndef RUSTFFI_H
#define RUSTFFI_H

#include <stdint.h>
#include <stdbool.h>

typedef struct {
    double x;
    double y;
} Point;

typedef struct {
    Point top_left;
    Point bottom_right;
} Rectangle;

typedef enum {
    STATUS_CODE_OK = 0,
    STATUS_CODE_INVALID_INPUT = 1,
    STATUS_CODE_OUT_OF_MEMORY = 2,
    STATUS_CODE_IO_ERROR = 3,
} StatusCode;

typedef struct {
    uint8_t *data;
    size_t len;
    size_t capacity;
} Buffer;

// Opaque 类型
typedef struct DatabaseConnection DatabaseConnection;

// 函数声明
int32_t rust_add(int32_t a, int32_t b);
StatusCode rust_process_rectangle(const Rectangle *rect, Rectangle *out);
DatabaseConnection *db_connect(const char *path);
void db_disconnect(DatabaseConnection *conn);

#endif /* RUSTFFI_H */
